[package]
name = "minecraft_model"
version = "0.1.0"
edition = "2021"

[[example]]
name = "demo"
path = "example/demo.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3.0"
